server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///rest_client?useSSL=false
    username: root
    password: 666666
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.65.128
    port: 5672
    username: kefan
    password: 666666
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo